[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyIsland"
version = "0.0.3"
authors = [
    { name = "星灿长风v(StarWindv)", email = "starwindv.stv@gmail.com"}
]
description = "Dynamic Island on Windows, written in Python"
readme = "./readme.md"
license = "GPL-3.0-only"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pyqt5",
    "asyncio>=3.4.3",
    "pillow>=11.3.0",
    "rich>=14.3.3",
    "keyboard>=0.13.5",
    "pytesseract>=0.3.13",
    "win_notice_lite>=0.1.2",
    "windows_bluetooth_watcher>=0.1.3",
    "flask>=3.1.3",
    "waitress>=3.0.2",
    "mss>=10.1.0",
    "pywin32>=311"
]
urls = { "Homepage" = "https://github.com/StarWindv/PyIsland" }

[project.scripts]
_island_instance = "PyIsland.instance:main"
island = "PyIsland.main:main"
