[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyIsland"
version = "0.0.3+Canary"
authors = [
    { name = "星灿长风v(StarWindv)", email = "starwindv.stv@gmail.com"}
]
description = "Dynamic Island on Windows, written in Python"
readme = "./readme.md"
license = "GPL-3.0-only"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pyqt5",
    "asyncio>=3.4.3",
    "wmi>=1.5.1",
    "pillow>=11.3.0",
    "rich>=14.2.0",
    "mss>=10.0.0",
    "keyboard>=0.13.5",
    "pytesseract>=0.3.13"
]
urls = { "Homepage" = "https://github.com/StarWindv/PyIsland" }

[project.scripts]
_island_instance = "PyIsland.instance:main"
island = "PyIsland.main:main"
