blank_issues_enabled: true
contact_links:
  - name: Security Report
    url: https://github.com/Python-island/Python-island/blob/Pyisland-Web/SECURITY.md
    about: Please report security vulnerabilities through the security policy channel.
